---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: redis-sweatshop-deployment
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: redis
    argocd.argoproj.io/instance: redis-sweatshop-deployment
    helm.sh/chart: redis-17.11.6
  name: redis-sweatshop-deployment-headless-external
  namespace: sweatshop-redis
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: tcp-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: redis-sweatshop-deployment
    app.kubernetes.io/name: redis
  sessionAffinity: None
  type: LoadBalancer
