apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sweat-shop-informer-deployment
  namespace: argocd
spec:
  project: app
  destination:
    name: dev11
    namespace: sweatshop
  source:
    repoURL: eu.gcr.io/stuttgart-things
    chart: sweatshop-informer
    targetRevision: v0.1.10
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            namespace: sweatshop
            redis:
              enabled: false
            configmaps:
              informer:
                INFORMING_NAMESPACE: machine-shop-packer
                INFORMING_KINDS: jobs
                REDIS_SERVER: redis-sweatshop-deployment-headless.sweatshop-redis.svc.cluster.local
                REDIS_PORT: "6379"
                REDIS_PASSWORD: <path:apps/data/sweatshop#redisPassword>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
