---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sweatshop-deployment
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: app
  destination:
    name: dev11
    namespace: sweatshop-redis
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 17.11.6
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            sentinel:
              enabled: true
            master:
              service:
                type: LoadBalancer
              persistence:
                enabled: false
                medium: ""
            replica:
              replicaCount: 1
              persistence:
                enabled: false
                medium: ""
            auth:
              password: <path:apps/data/sweatshop#redisPassword>
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true